FROM tensorflow/tensorflow:latest-py3

COPY *.py /home/
COPY train-data/ /home/train-data
COPY models/ /home/models
COPY data/ /home/data

USER root

RUN apt-get update -yq && apt-get install -yq vim && yes | pip install nltk

USER $NB_UID

WORKDIR /home/
RUN rm -rf /notebooks/

CMD ["bash"]
#CMD ["python", "lstm.py"]
