FROM tensorflow/tensorflow:latest-gpu-py3

COPY *.py /home/
COPY train-data/ /home/train-data
COPY models/ /home/models
COPY data/ /home/data
COPY logs/ /home/logs

RUN apt-get update -yq && apt-get install -yq vim && yes | pip install nltk

WORKDIR /home/
RUN rm -rf /notebooks/

CMD ["python", "lstm.py"]
